const Solution   = require('../models/Solution');
const Service    = require('../models/Service');
const Article    = require('../models/Article');
const Gallery    = require('../models/Gallery');
const Testimonial = require('../models/Testimonial');

module.exports = async function seed() {
  try {
    // Only seed if collections are empty
    const [sc, svc, art, gal, tes] = await Promise.all([
      Solution.countDocuments(),
      Service.countDocuments(),
      Article.countDocuments(),
      Gallery.countDocuments(),
      Testimonial.countDocuments(),
    ]);

    if (sc === 0) await Solution.insertMany([
      { title: 'AI Virtual Assistant', icon: '🤖', category: 'AI', tags: ['NLP','Chatbot','24/7'], desc: 'Intelligent conversational AI that handles customer queries, ticket routing, and HR FAQs — trained on your internal knowledge base.', full: 'Our AI Virtual Assistant leverages state-of-the-art large language models fine-tuned on your company\'s documentation. It integrates natively with Slack, Teams, Zendesk, and ServiceNow.\n\nKey outcomes include 60% reduction in Tier-1 support tickets, 24/7 availability across time zones, and seamless escalation to human agents when needed.', features: ['Natural Language Processing','Multi-channel deployment','Seamless human handoff','Real-time analytics dashboard','Enterprise SSO support','GDPR-compliant data handling'], order: 1 },
      { title: 'Rapid Prototyping Suite', icon: '⚡', category: 'Dev Tools', tags: ['Low-code','Rapid','API'], desc: 'Drag-and-drop AI-assisted prototyping that turns Figma mockups into deployable code in hours, not weeks.', full: 'The Rapid Prototyping Suite uses AI code generation to bridge the gap between design and development. Your team describes features in plain English and receives production-ready components.\n\nIntegrates with GitHub, GitLab, and Azure DevOps for seamless CI/CD.', features: ['AI code generation','Figma-to-code export','Component library builder','REST API scaffolding','Automated unit test generation','One-click staging deploy'], order: 2 },
      { title: 'Digital Employee Hub', icon: '🏢', category: 'HR Tech', tags: ['Employee','Portal','HR'], desc: 'A unified self-service portal that lets staff manage HR tasks, IT requests, and onboarding — all via one intelligent interface.', full: 'The Digital Employee Hub consolidates fragmented HR and IT systems into a single pane of glass.\n\nIncludes AI-powered search, automated approval workflows, and manager dashboards.', features: ['Unified service portal','AI-powered search','Automated approval workflows','Onboarding automation','Manager dashboards','Mobile-first design'], order: 3 },
      { title: 'Predictive Analytics Engine', icon: '📊', category: 'Analytics', tags: ['ML','Insights','Data'], desc: 'Machine learning dashboards that forecast churn, predict ticket volumes, and surface hidden operational inefficiencies.', full: 'Our Predictive Analytics Engine connects to your existing data warehouse and applies pre-trained ML models for workforce analytics.\n\nSupports BigQuery, Snowflake, and SQL Server.', features: ['Churn prediction','Workload forecasting','NL query interface','Automated anomaly detection','Exportable reports','API-first architecture'], order: 4 },
      { title: 'AI Document Processor', icon: '📄', category: 'Automation', tags: ['OCR','NLP','Documents'], desc: 'Intelligent document extraction that reads invoices, contracts, and forms — automatically routing data to downstream systems.', full: 'Powered by computer vision and NLP, the Document Processor achieves 99.2% extraction accuracy on structured documents.\n\nConnects to SAP, Oracle, and Microsoft Dynamics with pre-built connectors.', features: ['Invoice & contract reading','OCR + NLP fusion','ERP system connectors','Audit trail logging','Exception handling workflows','Multi-language support'], order: 5 },
      { title: 'Custom AI Integration', icon: '🔗', category: 'Enterprise', tags: ['Custom','API','Enterprise'], desc: 'Bespoke AI layer bolted onto your existing stack — no rip-and-replace. We work with what you already have.', full: 'For enterprises with established systems, we build custom AI connectors and middleware that layer intelligence on top of legacy infrastructure.\n\nWhether you need LLM integration, computer vision, or predictive modelling, our team architects the solution.', features: ['Legacy system integration','Custom model training','White-label options','On-premise deployment','Dedicated solution architect','SLA-backed support'], order: 6 },
    ]);

    if (svc === 0) await Service.insertMany([
      { title: 'AI Consulting & Strategy', icon: 'fa-lightbulb', tag: 'Strategy', tagType: 'tag-gold', desc: 'We map your processes, identify AI opportunities, and deliver a clear roadmap with ROI projections.', features: [['AI readiness assessment','fa-check'],['Process mapping & gap analysis','fa-check'],['ROI modelling','fa-check'],['Technology selection','fa-check'],['Board-ready strategy deck','fa-check'],['Quarterly review cadence','fa-check']], order: 1 },
      { title: 'Custom Software Development', icon: 'fa-code', tag: 'Build', tagType: 'tag-indigo', desc: 'Full-stack development of web apps, APIs, and AI-powered platforms. We write clean, tested, documented code.', features: [['React / Vue / Angular front-end','fa-code'],['Node.js / Python / .NET back-end','fa-code'],['REST & GraphQL APIs','fa-code'],['Cloud deployment (AWS / Azure / GCP)','fa-code'],['Automated CI/CD pipelines','fa-code'],['Comprehensive test suites','fa-code']], order: 2 },
      { title: 'AI Model Training & MLOps', icon: 'fa-brain', tag: 'AI/ML', tagType: 'tag-green', desc: 'From data preparation to production monitoring, we manage the full ML lifecycle for your bespoke models.', features: [['Training data curation','fa-database'],['Model fine-tuning & evaluation','fa-database'],['MLOps pipeline setup','fa-database'],['Model drift monitoring','fa-database'],['A/B testing framework','fa-database'],['Cost-optimised inference','fa-database']], order: 3 },
      { title: 'Integration & Migration', icon: 'fa-shuffle', tag: 'Integration', tagType: 'tag-gold', desc: 'Seamlessly connect your existing tools with new AI systems — no downtime, no data loss.', features: [['Legacy API wrapping','fa-link'],['ETL data pipeline build','fa-link'],['ERP & CRM connectors','fa-link'],['Zero-downtime migrations','fa-link'],['Data quality auditing','fa-link'],['Post-migration monitoring','fa-link']], order: 4 },
      { title: 'Support & Managed Services', icon: 'fa-headset', tag: 'Support', tagType: 'tag-indigo', desc: '24/7 monitoring, proactive alerting, and a dedicated account manager who knows your system inside-out.', features: [['24/7 infrastructure monitoring','fa-shield'],['SLA-backed response times','fa-shield'],['Monthly performance reports','fa-shield'],['Dedicated account manager','fa-shield'],['Security patching & updates','fa-shield'],['Disaster recovery planning','fa-shield']], order: 5 },
      { title: 'Training & Change Management', icon: 'fa-graduation-cap', tag: 'Training', tagType: 'tag-green', desc: 'We don\'t just build — we upskill your team to confidently own and evolve the solution after handover.', features: [['Bespoke user training sessions','fa-users'],['Admin & developer workshops','fa-users'],['Video library & documentation','fa-users'],['Change management planning','fa-users'],['Adoption metric tracking','fa-users'],['On-site or remote delivery','fa-users']], order: 6 },
    ]);

    if (art === 0) await Article.insertMany([
      { title: 'How AI Virtual Assistants Are Redefining Employee Support', category: 'AI Trends', author: 'Priya Sharma', thumb: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80', excerpt: 'The modern help desk is transforming. AI virtual assistants now handle over 60% of Tier-1 support queries, freeing human agents for the complex problems that truly matter.', full: 'AI virtual assistants have evolved from simple FAQ bots to genuinely intelligent systems that can reason, escalate, and personalise their responses.\n\nThe most successful deployments share three traits: deep integration with existing ticketing systems, a well-designed human handoff protocol, and continuous feedback loops that improve accuracy over time.\n\nCompanies that have deployed AI virtual assistants report average response times dropping from 4 hours to 47 seconds, while customer satisfaction scores have risen by an average of 22 points.', tags: ['AI','Virtual Assistants','HR Tech'] },
      { title: 'Rapid Prototyping with LLMs: From Idea to Demo in 72 Hours', category: 'Dev Tools', author: 'Marcus Okafor', thumb: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&q=80', excerpt: 'The age of months-long prototyping is over. Here\'s how forward-thinking teams are using AI code generation to collapse the idea-to-demo cycle.', full: 'The traditional prototyping cycle has barely changed in two decades. LLMs are now disrupting every stage simultaneously.\n\nModern AI code assistants can generate full React component trees from a Figma export, scaffold REST APIs from an OpenAPI spec, and write integration test suites from plain-English acceptance criteria.\n\nThe key mindset shift is treating LLM output as a first draft, not a finished product.', tags: ['Dev Tools','LLMs','Prototyping'] },
      { title: 'The Business Case for Predictive HR Analytics in 2025', category: 'Analytics', author: 'Dr. Aisha Nkosi', thumb: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80', excerpt: 'Why top HR teams are trading reactive dashboards for forward-looking ML models — and what it means for workforce planning.', full: 'Reactive HR reporting answers "what happened." Predictive analytics answers "what will happen and why."\n\nModern predictive HR systems ingest dozens of signals — engagement survey scores, meeting attendance, performance review cadences — to surface employees at risk of disengagement months before they hand in notice.\n\nFor workforce planning, organisations can predict hiring needs by team, by quarter, and by skill set.', tags: ['Analytics','HR Tech','ML'] },
      { title: 'Document AI: Why Manual Data Entry Is a Thing of the Past', category: 'Automation', author: 'Leon Baptiste', thumb: 'https://images.unsplash.com/photo-1597733336794-12d05021d510?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dXJsfGVufDB8fDB8fHww', excerpt: 'Intelligent document processing now achieves accuracy rates above 99% on structured forms. Here\'s the ROI.', full: 'Every organisation drowns in documents — invoices, purchase orders, contracts, onboarding forms. Manual processing is slow, error-prone, and deeply unpopular.\n\nThe technology stack combines optical character recognition for image-to-text, named entity recognition for extracting key fields, and large language models for understanding context.\n\nA mid-sized logistics firm we worked with processes 4,000 invoices per month. After deploying our Document AI, their processing time dropped from 3 days to 4 hours.', tags: ['Automation','Document AI','OCR'] },
      { title: 'Building a Culture of AI Adoption: Lessons from 50 Deployments', category: 'Culture', author: 'Priya Sharma', thumb: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&q=80', excerpt: 'The technology is rarely the hard part. After 50 AI deployments, here\'s what we\'ve learned about the human side.', full: 'Technology adoption fails not because the technology is bad, but because the change management is inadequate.\n\nThe interventions that make the biggest difference are: executive sponsorship that is visible and sustained, peer champions embedded in each team, quick wins documented and shared widely in the first 90 days, and honest feedback loops.\n\nChange management is not a soft add-on. It is the difference between ROI and write-off.', tags: ['Culture','Change Management','Enterprise'] },
      { title: 'Five AI Trends Shaping Enterprise Software in 2025', category: 'AI Trends', author: 'Marcus Okafor', thumb: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&q=80', excerpt: 'From agentic AI to on-device inference, these are the shifts every enterprise technology leader should be watching.', full: '1. Agentic AI: Systems that autonomously complete multi-step tasks without human hand-holding at each stage.\n\n2. On-device inference: Running smaller, fine-tuned models on-device for privacy-sensitive applications.\n\n3. Multimodal enterprise tools: AI that sees, reads, and listens — processing documents, voice calls, and video all within a single workflow.\n\n4. AI observability: Dedicated tooling for monitoring model behaviour in regulated industries.\n\n5. Cost-first model selection: Teams are optimising for cost-per-query, choosing the smallest model that meets the quality bar.', tags: ['AI Trends','Enterprise','2025'] },
    ]);

    if (gal === 0) await Gallery.insertMany([
      { title: 'Innovation Summit 2025', category: 'Events', img: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80', order: 1 },
      { title: 'AI Demo Day — Manchester', category: 'Demo Days', img: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600&q=80', order: 2 },
      { title: 'Team Hackathon 2024', category: 'Team', img: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600&q=80', order: 3 },
      { title: 'Product Launch — AI Hub', category: 'Launch Events', img: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&q=80', order: 4 },
      { title: 'Client Workshop — London', category: 'Events', img: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80', order: 5 },
      { title: 'Sunderland Office Opening', category: 'Team', img: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&q=80', order: 6 },
      { title: 'Tech Conference Panel', category: 'Events', img: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&q=80', order: 7 },
      { title: 'AI Solutions Demo — Birmingham', category: 'Demo Days', img: 'https://images.unsplash.com/photo-1512236258305-32fb110fdb01?w=600&q=80', order: 8 },
      { title: 'End of Year Celebration', category: 'Team', img: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&q=80', order: 9 },
    ]);

    if (tes === 0) await Testimonial.insertMany([
      { name: 'Sarah Mitchell', role: 'CTO, TechNova UK', company: 'TechNova', rating: 5, text: 'AI-Solutions deployed their virtual assistant into our helpdesk in under 3 weeks. First-contact resolution jumped 58% and our support team now focuses on genuinely complex problems. The ROI was evident within the first month.' },
      { name: 'James Ogundimu', role: 'Head of Digital, Orbis Group', company: 'Orbis Group', rating: 5, text: 'The team\'s depth of knowledge is matched only by their honesty about what AI can and cannot do. They delivered exactly what they promised — not more, not less — and on time. That reliability is rare.' },
      { name: 'Dr. Fatima Al-Hassan', role: 'Director of Operations, Meridian Labs', company: 'Meridian Labs', rating: 5, text: 'Our document processing backlog was costing us 3 FTE worth of manual effort every week. After the AI-Solutions implementation, that\'s down to half a day. The accuracy is genuinely better than human review.' },
      { name: 'Tom Weston', role: 'VP Engineering, Synapse Co.', company: 'Synapse Co.', rating: 5, text: 'We\'d been burned by an AI vendor before — overpromised, underdelivered. AI-Solutions won us over with a realistic pilot scope and then exceeded our expectations. We\'ve now rolled out to 4 additional departments.' },
      { name: 'Abena Mensah', role: 'HR Director, QuantumEdge', company: 'QuantumEdge', rating: 5, text: 'The training sessions they ran for our staff were genuinely excellent. Not just "here\'s how to use it" but "here\'s why it works and how to improve it." Our team now champions the tool rather than fearing it.' },
      { name: 'Raj Patel', role: 'People Analytics Lead, DataCore Ltd', company: 'DataCore', rating: 5, text: 'Predictive analytics surfaced an engagement risk in one of our highest-performing teams 6 weeks before annual review season. We acted early and retained three key engineers. That alone justified the entire project cost.' },
    ]);

    console.log('✅ Database seeded');
  } catch (err) {
    console.warn('Seed warning:', err.message);
  }
};
